### ISSUE TITLE
Calling Formula.sha1 is deprecated

### ISSUE THREAD

**Issue by Blackskyliner** [eddieantonio/homebrew-eddieantonio#1]
Today I updated and I got a warning regarding your homebrew package.

I will quote `brew` on that issue:

> Warning: Calling Formula.sha1 is deprecated!
> Use Formula.sha256 instead.
> /usr/local/Library/Taps/eddieantonio/homebrew-eddieantonio/imgcat.rb:4:in `class:Imgcat'

**Comment by eddieantonio** [comment]
Thanks for reporting this! I updated this formula to use the sha256 hash instead!
